repos:
  - repo: https://github.com/pycqa/isort
    rev: "5.10.1"
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: "v3.3.1"
    hooks:
      - id: pyupgrade
        args: [--py311-plus]
  - repo: https://github.com/ambv/black
    rev: "22.12.0"
    hooks:
      - id: black-jupyter
        args: [--target-version=py311]
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.0.0-alpha.4"
    hooks:
      - id: prettier
